source 'https://rubygems.org'
gem 'fastreader'
gem 'nokogiri', '1.6.0', :git => 'https://github.com/sparklemotion/nokogiri.git'
gem 'rack', '~> 1.6', '>= 1.6.12'
gem 'rspec', :git => 'https://github.com/rspec/rspec.git'
gem 'pdfkit', '~> 0.5'
