source 'https://rubygems.org'
gem 'fastreader', '>= 1.0.8'
gem 'nokogiri', '1.6.0', :git => 'https://github.com/sparklemotion/nokogiri.git'
gem 'rack', '~> 1.1'
gem 'rspec', :git => 'https://github.com/rspec/rspec.git'
gem 'pdfkit', '~> 0.5'
